### ISSUE TITLE
Sporadic error when loading some JS applications requiring iotivity-node

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#110]
I have seen the following error on the gateway today when attempting to start the `smarthome` service. I had seen a similar error on a different board running the `solar.js` service. I don't know how to reliably reproduce this as the problem disappeared after a few reboots although we had not changed anything on the image. There are actually two problems showing on the log below, the one that this issue is about is the error while loading `iotivity-node`. Somehow, `modules.js` cannot find it although it's on the rootfs.

The second problem that appears is that when this happens, `systemd` will attempt to restart the service but it continues to fail in the same way until we the 'start-limit-hit' error at which point I believe systemd stops attempting to restart the service.

Here is the relevant log:
```
root@gateway:~# cat smarthome.log
-- Logs begin at Wed 2017-03-01 09:36:12 UTC, end at Wed 2017-03-01 10:20:26 UTC. --
Mar 01 09:45:19 gateway systemd[1]: Stopping Home gateway server...
Mar 01 09:45:19 gateway systemd[1]: Stopped Home gateway server.
Mar 01 09:45:19 gateway systemd[1]: Started Home gateway server.
Mar 01 10:13:02 gateway systemd[1]: Stopping Home gateway server...
Mar 01 10:13:02 gateway systemd[1]: Stopped Home gateway server.
Mar 01 10:13:02 gateway systemd[1]: Started Home gateway server.
Mar 01 10:13:15 gateway systemd[1]: Stopping Home gateway server...
Mar 01 10:13:15 gateway systemd[1]: Stopped Home gateway server.
Mar 01 10:13:15 gateway systemd[1]: Started Home gateway server.
Mar 01 10:13:16 gateway node[1376]: module.js:327
Mar 01 10:13:16 gateway node[1376]:     throw err;
Mar 01 10:13:16 gateway node[1376]:     ^
Mar 01 10:13:16 gateway node[1376]: Error: Cannot find module 'iotivity-node'
Mar 01 10:13:16 gateway node[1376]:     at Function.Module._resolveFilename (module.js:325:15)
Mar 01 10:13:16 gateway node[1376]:     at Function.Module._load (module.js:276:25)
Mar 01 10:13:16 gateway node[1376]:     at Module.require (module.js:353:17)
Mar 01 10:13:16 gateway node[1376]:     at require (internal/module.js:12:17)
Mar 01 10:13:16 gateway node[1376]:     at Object.<anonymous> (/home/root/SmartHome-Demo/gateway/gateway-server.js:1:76)
Mar 01 10:13:16 gateway node[1376]:     at Module._compile (module.js:409:26)
Mar 01 10:13:16 gateway node[1376]:     at Object.Module._extensions..js (module.js:416:10)
Mar 01 10:13:16 gateway node[1376]:     at Module.load (module.js:343:32)
Mar 01 10:13:16 gateway node[1376]:     at Function.Module._load (module.js:300:12)
Mar 01 10:13:16 gateway node[1376]:     at Function.Module.runMain (module.js:441:10)
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Unit entered failed state.
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Failed with result 'exit-code'.
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Service hold-off time over, scheduling restart.
Mar 01 10:13:16 gateway systemd[1]: Stopped Home gateway server.
Mar 01 10:13:16 gateway systemd[1]: Started Home gateway server.
Mar 01 10:13:16 gateway node[1404]: module.js:327
Mar 01 10:13:16 gateway node[1404]:     throw err;
Mar 01 10:13:16 gateway node[1404]:     ^
Mar 01 10:13:16 gateway node[1404]: Error: Cannot find module 'iotivity-node'
Mar 01 10:13:16 gateway node[1404]:     at Function.Module._resolveFilename (module.js:325:15)
Mar 01 10:13:16 gateway node[1404]:     at Function.Module._load (module.js:276:25)
Mar 01 10:13:16 gateway node[1404]:     at Module.require (module.js:353:17)
Mar 01 10:13:16 gateway node[1404]:     at require (internal/module.js:12:17)
Mar 01 10:13:16 gateway node[1404]:     at Object.<anonymous> (/home/root/SmartHome-Demo/gateway/gateway-server.js:1:76)
Mar 01 10:13:16 gateway node[1404]:     at Module._compile (module.js:409:26)
Mar 01 10:13:16 gateway node[1404]:     at Object.Module._extensions..js (module.js:416:10)
Mar 01 10:13:16 gateway node[1404]:     at Module.load (module.js:343:32)
Mar 01 10:13:16 gateway node[1404]:     at Function.Module._load (module.js:300:12)
Mar 01 10:13:16 gateway node[1404]:     at Function.Module.runMain (module.js:441:10)
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Unit entered failed state.
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Failed with result 'exit-code'.
Mar 01 10:13:16 gateway systemd[1]: smarthome.service: Service hold-off time over, scheduling restart.
Mar 01 10:13:16 gateway systemd[1]: Stopped Home gateway server.
Mar 01 10:13:17 gateway systemd[1]: Started Home gateway server.
Mar 01 10:13:17 gateway node[1412]: module.js:327
Mar 01 10:13:17 gateway node[1412]:     throw err;
Mar 01 10:13:17 gateway node[1412]:     ^
Mar 01 10:13:17 gateway node[1412]: Error: Cannot find module 'iotivity-node'
Mar 01 10:13:17 gateway node[1412]:     at Function.Module._resolveFilename (module.js:325:15)
Mar 01 10:13:17 gateway node[1412]:     at Function.Module._load (module.js:276:25)
Mar 01 10:13:17 gateway node[1412]:     at Module.require (module.js:353:17)
Mar 01 10:13:17 gateway node[1412]:     at require (internal/module.js:12:17)
Mar 01 10:13:17 gateway node[1412]:     at Object.<anonymous> (/home/root/SmartHome-Demo/gateway/gateway-server.js:1:76)
Mar 01 10:13:17 gateway node[1412]:     at Module._compile (module.js:409:26)
Mar 01 10:13:17 gateway node[1412]:     at Object.Module._extensions..js (module.js:416:10)
Mar 01 10:13:17 gateway node[1412]:     at Module.load (module.js:343:32)
Mar 01 10:13:17 gateway node[1412]:     at Function.Module._load (module.js:300:12)
Mar 01 10:13:17 gateway node[1412]:     at Function.Module.runMain (module.js:441:10)
Mar 01 10:13:17 gateway systemd[1]: smarthome.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 10:13:17 gateway systemd[1]: smarthome.service: Unit entered failed state.
Mar 01 10:13:17 gateway systemd[1]: smarthome.service: Failed with result 'exit-code'.

<snip>

Mar 01 10:14:14 gateway systemd[1]: Started Home gateway server.
Mar 01 10:14:14 gateway node[1484]: module.js:327
Mar 01 10:14:14 gateway node[1484]:     throw err;
Mar 01 10:14:14 gateway node[1484]:     ^
Mar 01 10:14:14 gateway node[1484]: Error: Cannot find module 'iotivity-node'
Mar 01 10:14:14 gateway node[1484]:     at Function.Module._resolveFilename (module.js:325:15)
Mar 01 10:14:14 gateway node[1484]:     at Function.Module._load (module.js:276:25)
Mar 01 10:14:14 gateway node[1484]:     at Module.require (module.js:353:17)
Mar 01 10:14:14 gateway node[1484]:     at require (internal/module.js:12:17)
Mar 01 10:14:14 gateway node[1484]:     at Object.<anonymous> (/home/root/SmartHome-Demo/gateway/gateway-server.js:1:76)
Mar 01 10:14:14 gateway node[1484]:     at Module._compile (module.js:409:26)
Mar 01 10:14:14 gateway node[1484]:     at Object.Module._extensions..js (module.js:416:10)
Mar 01 10:14:14 gateway node[1484]:     at Module.load (module.js:343:32)
Mar 01 10:14:14 gateway node[1484]:     at Function.Module._load (module.js:300:12)
Mar 01 10:14:14 gateway node[1484]:     at Function.Module.runMain (module.js:441:10)
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Unit entered failed state.
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Failed with result 'exit-code'.
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Service hold-off time over, scheduling restart.
Mar 01 10:14:14 gateway systemd[1]: Stopped Home gateway server.
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Start request repeated too quickly.
Mar 01 10:14:14 gateway systemd[1]: Failed to start Home gateway server.
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Unit entered failed state.
Mar 01 10:14:14 gateway systemd[1]: smarthome.service: Failed with result 'start-limit-hit'.
```

**Comment by nagineni** [comment]
> Mar 01 10:14:14 gateway node[1484]: Error: Cannot find module 'iotivity-node'

This can happen only when the NODE_PATH is not set correctly. /etc/profile should set this environment variable on the gateway with Refkit/Ostro image by default. No idea why it failed.

**Comment by gvancuts** [comment]
This smells a bit like a race condition during start-up... this will be a tricky one to root-cause.
