### ISSUE TITLE
Unable to start OCF server javascripts

### ISSUE THREAD

**Issue by pcaston** [01org/SmartHome-Demo#182]
I am connecting to the 'Connected Smart Home' Intel Edison Arduino board and Grove devices from Windows 10 using Putty.

**When I launch the java scripts as background processes I get the following error. **

Error: Cannot find module 'lodash.mergewith'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/home/root/SmartHome-Demo/ocf-servers/js-servers/config/json-to-cbor.js:27:13)
    at Object.<anonymous> (/home/root/SmartHome-Demo/ocf-servers/js-servers/motion.js:43:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**If I launch them with the –no-secure option I get this error**

node ocf-servers/js-servers/gas.js –no-secure &

TypeError: Cannot convert undefined or null to object
    at Function.assign (native)
    at Object.<anonymous> (/home/root/SmartHome-Demo/ocf-servers/js-servers/motion.js:148:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by ttzeng** [comment]
@pcaston what image did you installed on the Edison board? and what's the node.js version?

**Comment by pcaston** [comment]
@ttzeng I installed the Ostro OS via the hyperlink:
ostro-image-swupd-dev-edison-2016-10-07_04-27-05-build-507.toflash.tar.bz2 
I can't check my machine at the moment but from memory it was node.js 4.5

**Comment by ttzeng** [comment]
@pcaston the Ostro 507 image built with iotivity-node 1.1.1-3 which is out of date. The master branch of the SmartHome-Demo repo now [depends on iotivity-node 1.3.0](https://github.com/01org/SmartHome-Demo/commit/6c32d4c222fe48d80cda9cb724fb9f41077b8f31), so it seems you were blocked by the mismatch of the iotivity-node versions.

**Comment by pcaston** [comment]
@ttzeng so I should use the latest Ostro version?

**Comment by ttzeng** [comment]
@pcaston Unfortunately the Ostro project does not upgrade components for months, it's still iotivity-node 1.1.1-3 included in the latest image. :(

Though I admit it's a bad idea, but if you only want to setup an OCF server to test with, and you won't enable the secure mode, you might consider to checkout the 1.1.1-3 release label for simplicity.

**Comment by pcaston** [comment]
@ttzeng many thanks.  I tried that suggestion and got the OCF server detection and control working through the mobile cordova app.  I saw the other issue about the tutorial needing an update, so I will work carefully through the suggestions made there to get the full system working.
