### ISSUE TITLE
Some errors ans crashes in the Docker container

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#35]
I have pulled the Docker container on my Linux (Fedora 24) system as follows:
- sudo docker run --name portal -p 3030:3000 -p 3031:4000 gvancuts/smarthome-demo

But I'm seeing a number of errors and tracebacks when inspecting the logs of the containes (see smarthome-container.txt attached).
[smarthome-container.txt](https://github.com/01org/SmartHome-Demo/files/511187/smarthome-container.txt)

**Comment by gvancuts** [comment]
@ichbinblau could you please take a look at this issue?

@ttzeng, fyi

**Comment by ichbinblau** [comment]
@gvancuts @ttzeng
This is due to an unresolved issue of supervisord [122]. (https://github.com/Supervisor/supervisor/issues/122#issuecomment-6024816)
As celery worker, web-portal and rabbitmq all depends on MySQL server, they start up at the same time even though I set up the priority in the config file. Usually a restart of the container would solve the problem after users set up the gateway info. 
I have created a new [pull request ](https://github.com/01org/SmartHome-Demo/pull/37)to solve this. Would you plz have a check again? Thanks!

**Comment by ttzeng** [comment]
With PR#37, now the docker image seems to pass the MySQL connection refused error. But it throws below errors:

[2016-10-12 03:02:32,706: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2016-10-12 03:02:32,712: INFO/MainProcess] mingle: searching for neighbors
[2016-10-12 03:02:33,719: INFO/MainProcess] mingle: all alone
[2016-10-12 03:02:33,727: WARNING/MainProcess] celery@e4c01c49957d ready.
[2016-10-12 03:02:33,728: INFO/MainProcess] Received task: CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525]
[2016-10-12 03:02:33,728: INFO/Worker-4] init database mysql+pymysql://root:intel123@localhost:3306/smart_home?charset=utf8
[2016-10-12 03:02:33,747: INFO/Worker-4] CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525]: Ready to proceed task: Base task Object.
[2016-10-12 03:02:33,750: WARNING/Worker-4] https://192.168.1.104:8000/api/oic/res
[2016-10-12 03:02:33,756: INFO/Worker-4] Starting new HTTPS connection (1): 192.168.1.104
[2016-10-12 03:02:33,801: ERROR/Worker-4] <class 'requests.exceptions.SSLError'> [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
[2016-10-12 03:02:33,801: ERROR/Worker-4] CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525]: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
[2016-10-12 03:02:33,817: INFO/MainProcess] Received task: CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]
[2016-10-12 03:02:33,818: INFO/MainProcess] Received task: CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525] eta:[2016-10-12 03:03:03.805100+00:00]
[2016-10-12 03:02:33,818: INFO/MainProcess] Task CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525] retry: Retry in 30s: IoTConnectionError(SSLError(SSLError(SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'),),),)
[2016-10-12 03:02:33,819: INFO/Worker-2] init database mysql+pymysql://root:intel123@localhost:3306/smart_home?charset=utf8
[2016-10-12 03:02:33,837: INFO/Worker-2] CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]: Ready to proceed task: Base task Object.
[2016-10-12 03:03:37,844: WARNING/Worker-8] https://192.168.1.104:8000/api/oic/res
[2016-10-12 03:03:37,851: INFO/Worker-8] Starting new HTTPS connection (1): 192.168.1.104
[2016-10-12 03:03:37,862: ERROR/Worker-8] <class 'requests.exceptions.SSLError'> [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
[2016-10-12 03:03:37,862: ERROR/Worker-8] CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525]: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
[2016-10-12 03:03:37,864: ERROR/Worker-8] <class 'requests.exceptions.SSLError'> [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
[2016-10-12 03:03:37,865: ERROR/MainProcess] <class 'requests.exceptions.SSLError'> [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
[2016-10-12 03:03:37,866: ERROR/MainProcess] Task CeleryTask.tasks.get_sensor_data[b3d586ae-bdf7-4e68-8a0e-ca57d3937525] raised unexpected: IoTConnectionError(SSLError(SSLError(SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'),),),)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/tasks.py", line 24, in get_sensor_data
    raise self.retry(exc=exc)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 670, in retry
    maybe_reraise()
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/__init__.py", line 242, in maybe_reraise
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/tasks.py", line 22, in get_sensor_data
    task_entry(mgr)
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/managers/base.py", line 33, in task_entry
    raise e
IoTConnectionError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
(496) accepted ('172.17.0.1', 59992)
(496) accepted ('172.17.0.1', 59994)
(496) accepted ('172.17.0.1', 59998)
(496) accepted ('172.17.0.1', 59999)
(496) accepted ('172.17.0.1', 60000)
2016-10-12 03:04:13,691 | INFO     | database.py-init-0074 | init database mysql+pymysql://root:intel123@localhost:3306/smart_home?charset=utf8
(496) accepted ('172.17.0.1', 60007)
(496) accepted ('172.17.0.1', 60009)
(496) accepted ('172.17.0.1', 60011)
Welcome ostro
2016-10-12 03:04:35,870 | INFO     | SHProject.py-test_connect-0105 | Connected.
(496) accepted ('172.17.0.1', 60014)
[2016-10-12 03:04:41,021: ERROR/Worker-2] <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc172d90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2016-10-12 03:04:41,022: ERROR/Worker-2] CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]: HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc172d90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2016-10-12 03:04:41,041: INFO/MainProcess] Received task: CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387] eta:[2016-10-12 03:05:11.026569+00:00]
[2016-10-12 03:04:41,042: INFO/MainProcess] Task CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387] retry: Retry in 30s: IoTConnectionError(ConnectionError(MaxRetryError("HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc172d90>: Failed to establish a new connection: [Errno 110] Connection timed out',))",),),)
[2016-10-12 03:05:11,907: INFO/Worker-6] init database mysql+pymysql://root:intel123@localhost:3306/smart_home?charset=utf8
[2016-10-12 03:05:11,939: INFO/Worker-6] CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]: Ready to proceed task: Base task Object.
[2016-10-12 03:05:11,942: WARNING/Worker-6] https://10.239.76.66:8000/api/oic/res
[2016-10-12 03:05:11,949: INFO/Worker-6] Starting new HTTPS connection (1): 10.239.76.66
[2016-10-12 03:07:19,229: ERROR/Worker-6] <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc18ba10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2016-10-12 03:07:19,230: ERROR/Worker-6] CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]: HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc18ba10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2016-10-12 03:07:19,246: INFO/MainProcess] Received task: CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387] eta:[2016-10-12 03:07:49.233706+00:00]
[2016-10-12 03:07:19,247: INFO/MainProcess] Task CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387] retry: Retry in 30s: IoTConnectionError(ConnectionError(MaxRetryError("HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc18ba10>: Failed to establish a new connection: [Errno 110] Connection timed out',))",),),)
[2016-10-12 03:07:50,089: INFO/Worker-1] init database mysql+pymysql://root:intel123@localhost:3306/smart_home?charset=utf8
[2016-10-12 03:07:50,113: INFO/Worker-1] CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]: Ready to proceed task: Base task Object.
[2016-10-12 03:07:50,117: WARNING/Worker-1] https://10.239.76.66:8000/api/oic/res
[2016-10-12 03:07:50,124: INFO/Worker-1] Starting new HTTPS connection (1): 10.239.76.66
[2016-10-12 03:09:57,436: ERROR/Worker-1] <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc174c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2016-10-12 03:09:57,437: ERROR/Worker-1] CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387]: HTTPSConnectionPool(host='10.239.76.66', port=8000): Max retries exceeded with url: /api/oic/res (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f65cc174c50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
[2016-10-12 03:09:57,438: ERROR/Worker-1] <class 'requests.exceptions.ConnectionError'> None: Max retries exceeded with url: /api/oic/res (Caused by None)
[2016-10-12 03:09:57,439: ERROR/MainProcess] <class 'requests.exceptions.ConnectionError'> None: Max retries exceeded with url: /api/oic/res (Caused by None)
[2016-10-12 03:09:57,439: ERROR/MainProcess] Task CeleryTask.tasks.get_sensor_data[e4ede0a2-64ae-4646-9498-575556715387] raised unexpected: IoTConnectionError(ConnectionError(MaxRetryError('None: Max retries exceeded with url: /api/oic/res (Caused by None)',),),)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/tasks.py", line 24, in get_sensor_data
    raise self.retry(exc=exc)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 670, in retry
    maybe_reraise()
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/__init__.py", line 242, in maybe_reraise
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/tasks.py", line 22, in get_sensor_data
    task_entry(mgr)
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/managers/base.py", line 33, in task_entry
    raise e
IoTConnectionError: None: Max retries exceeded with url: /api/oic/res (Caused by None)
(496) accepted ('172.17.0.1', 60084)
(496) accepted ('172.17.0.1', 60085)
(496) accepted ('172.17.0.1', 60087)
(496) accepted ('172.17.0.1', 60088)
temperature [u'2016-10-11 16:00:00', u'2016-10-12 15:59:59']
[]
gas [u'2016-10-11 16:00:00', u'2016-10-12 15:59:59']
[]
illuminance [u'2016-10-11 16:00:00', u'2016-10-12 15:59:59']
[]
buzzer [u'2016-10-11 16:00:00', u'2016-10-12 15:59:59']
[]
2016-10-12 03:14:00,863 | INFO     | SHProject.py-test_disconnect-0112 | Client disconnected

**Comment by wanghongjuan** [comment]
@ichbinblau I have the same error with @ttzeng and have other error which message like `IoTRequestError: IoT request failed (404)`, show a part of information:
```
[2016-10-18 11:08:52,443: INFO/Worker-2] Status code 404: IoT request failed
[2016-10-18 11:08:52,444: WARNING/Worker-2] Exception in thread 66326334-6537-6231-2d66-3138322d3434:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/SmartHome-Demo/smarthome-web-portal/CeleryTask/managers/data_manager.py", line 51, in run
    self.client_conn.get_data(stream=True, callback=self.parse_data, **kargs)
  File "/opt/SmartHome-Demo/smarthome-web-portal/RestClient/sensor.py", line 51, in get_data
    self.resp.get_data(callback, **kargs)
  File "/opt/SmartHome-Demo/smarthome-web-portal/RestClient/api/__init__.py", line 190, in get_data
    raise IoTRequestError(self.status_code)
IoTRequestError: IoT request failed (404)
```
please see below attachment about the detail information.
[docker-running-log.txt](https://github.com/01org/SmartHome-Demo/files/537778/docker-running-log.txt)

**Comment by ichbinblau** [comment]
Hi, @wanghongjuan. Tonny got this error cos his gateway use http protocol instead of https. Plz firstly make sure that the gateway is accessible at the gateway IP you updated in the admin portal. As for the second error message, it means that the sensor (guid =66326334-6537-6231-2d66-3138322d3434) was not found. Plz confirm that you can get the sensor data <gateway-ip>:8000/api/a/<sensor_type>?di=66326334-6537-6231-2d66-3138322d3434

**Comment by wanghongjuan** [comment]
@ichbinblau Thanks for the information, it is make sense to me. I tried to add my gateway which connected more sensers to the admin portal, but got the same sensors information as your gateway. Actually, I got a different uuid when run the sensor fan on my local gateway, so I can not access `<my-gateway-ip>:8000/api/a/fan?di=66326334-6537-6231-2d66-3138322d3434`. I think this is weird. Is there anything wrong when run this image? BTW, do you have any solution that can resolve how to build the image including my gateway?

**Comment by ichbinblau** [comment]
@wanghongjuan you may refer to the guide in the [README.md](https://github.com/01org/SmartHome-Demo/tree/master/smarthome-web-portal/tools/docker) (step 5).

**Comment by wanghongjuan** [comment]
Thanks, For the second question, it works now.

**Comment by ichbinblau** [comment]
Hi, @wanghongjuan The first error is due to he multiply gateways configured in admin portal. One is them is unreachable (does not exist). The error will be gone if you remove the other gateway.

**Comment by wanghongjuan** [comment]
@ichbinblau thanks for your information.There is an issue when I want to delete the exist gateway: `Internal Server Error(500): The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.` But it's fine when I delete the new added gateway. Do u have this issue? I tired to update the gateway IP and geo location for gateway "demo" to my gateway, restart the docker service, then check the log show all information of sensors which connected on my gateway.

**Comment by ichbinblau** [comment]
Hi, @wanghongjuan. I can also reproduce it. I will fix this.  Thanks

**Comment by wanghongjuan** [comment]
Hi, @ichbinblau I create a new ticket(#49) to track the delete issue. Actually this crash issue has been fixed, so I think we can close it now. How do you think about this?

**Comment by ichbinblau** [comment]
Hi, @wanghongjuan. Yes, this issue has been fixed, You may want to close it. Thank you.

**Comment by wanghongjuan** [comment]
It seems that only the reporter of this issue can close it. @gvancuts could you please close this issue?

**Comment by gvancuts** [comment]
Sure, closing as per previous comments.
