### ISSUE TITLE
Rules engine is missing

### ISSUE THREAD

**Issue by poussa** [01org/SmartHome-Demo#7]
`npm install`
`node first_server.js`

module.js:327
    throw err;
    ^

Error: Cannot find module './dollhouse/rules_engine'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/spoussa/src/iot/SmartHome-Demo/first_server.js:16:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by ralf-graefe** [comment]
I also noticed that. first_server.js is referring at 2 locations to the dollhouse directory. However the path name has changed to gateway-webui.

Changing directory name in script solves it.

Ralf

**Comment by poussa** [comment]
@ralf-graefe can you send a path to fix it ?

**Comment by ralf-graefe** [comment]
Yes, I am traveling, will do this evening.

Ralf

**Comment by ralf-graefe** [comment]
Here is the little fix:


--- first_server.orig
+++ first_server.js
@@ -4,7 +4,7 @@
     , app = express()
     , systemd = require('systemd');

-app.use(express.static(__dirname + '/dollhouse'));
+app.use(express.static(__dirname + '/gateway-webui'));

var fs = require('fs');
var vm = require('vm');
@@ -13,7 +13,7 @@
     vm.runInThisContext(code, path);
}.bind(this);

-var rules = require('./dollhouse/rules_engine');
+var rules = require('./gateway-webui/rules_engine');

var fs = require('fs');
console.log(__dirname + "/data.json");


Ralf

**Comment by gvancuts** [comment]
Unless I've missed something, the fix for this was merged in https://github.com/01org/SmartHome-Demo/pull/8. I'm therefore closing this ticket, let me know if it needs to be re-opened.
